version: '3.8'

services:
  arkham:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: on-failure
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=arkham_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    extra_hosts:
      - "host.docker.internal:host-gateway" 